accuracy.o: accuracy.F90
accuracy.o = accuracy.o
_mod_accuracy: accuracy.o
_mod_accuracy = $(accuracy.o)

allocate.o: allocate.F90 assert.h
allocate.o = allocate.o $(assert.h)
_mod_allocation: allocate.o
_mod_allocation = $(allocate.o)

assert.o: assert.F90
assert.o = assert.o
_mod_assert: assert.o
_mod_assert = $(assert.o)

constants.o: constants.F90 _mod_accuracy
constants.o = constants.o $(_mod_accuracy)
_mod_constants: constants.o
_mod_constants = $(constants.o)

memman.o: memman.F90 _mod_accuracy
memman.o = memman.o $(_mod_accuracy)
_mod_memman: memman.o
_mod_memman = $(memman.o)

unitconversion.o: unitconversion.F90 _mod_constants
unitconversion.o = unitconversion.o $(_mod_constants)
_mod_unitconversion: unitconversion.o
_mod_unitconversion = $(unitconversion.o)

